/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Is the process alive and able to respond at all? No dependency
         *     checks - this endpoint answering means the ASGI server and this
         *     process are up, nothing more.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Can this app actually do useful work right now?
         *
         *     Database and object storage are the two dependencies this chapter
         *     actually checks live - a bounded, real "SELECT 1" through the
         *     restricted tenderpilot_app role (see db.py), and a bounded, real,
         *     read-only HeadBucket through that same restricted identity against
         *     SeaweedFS (see storage.py). Everything else in dependencies comes
         *     from config.get_dependency_status(), which never does I/O - a
         *     "credentials_present" there is never conflated with "verified
         *     working" here.
         *
         *     Timeout ordering (see BOOK.md's chapter on this): both checks are
         *     capped at 2s (db.DATABASE_HEALTH_CHECK_TIMEOUT_SECONDS and
         *     storage.STORAGE_HEALTH_CHECK_TIMEOUT_SECONDS), which stays
         *     comfortably under this route's own callers' timeouts
         *     (apps/web/app/api/health/route.ts's 5s fetch, and the frontend
         *     poller's 6s check timeout) - each outer layer must be able to wait
         *     long enough for the layer it calls to finish on its own, or it ends
         *     up reporting a generic "timed out" instead of the real, specific
         *     answer the inner layer would have given.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
            /** App Env */
            app_env: string;
            /** Dependencies */
            dependencies: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
